### ISSUE TITLE
Implement “Invalid Email” error handling

### ISSUE THREAD

**Issue by alastairong** [Holo-Host/holo-auth#12]
If IsWhiteListed check returns something falsey we should send an “Invalid Email” email for easier troubleshooting.

Template text found here: https://hackmd.io/_D_JAX7qS9a14GVbE-3vtA?edit

This should be implemented before deploying holo-auth to production.

**Comment by yegortimoshenko** [comment]
Done in #13. Thanks for bringing this up.
