### ISSUE TITLE
Fix HoloPort URL in challenge email

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-auth#14]
cc @alastairong @jarodholtz

I noticed that the following part of `challenge` template:

```html
<a href="https://{{holochain_agent_id}}.holohost.net">{{holochain_agent_id}}.holohost.net</a>
```

Has been changed to:

```html
<p>https://{{holochain_agent_id}}.holohost.net</p>
```

I'm not sure what the motivation is. I'd guess that it was made into text rather than a link because we previously had "Link not working?" text there, and that no longer applies, it's a completely different link to the one that is used as part of the button.

Additionally, I optimized the template so that the entire address would fit, and because `https://` is now visible part of this line, it no longer fits:

![Screenshot from 2020-01-30 09-19-49](https://user-images.githubusercontent.com/1643293/73436053-b19ccd00-4341-11ea-86f5-70accfd58f0e.png)

Unless anyone minds otherwise, can I revert this back? If no, I'll just close this because this is way too minor to have an argument over.

**Comment by alastairong** [comment]
The motivation to make it not a link is to reduce the chance of someone clicking it instead of the button and thereby trying to access HP Admin before registration has completed.

If this will automatically redirect to hpstatus then maybe it's not a problem, but I would suggest we just close it and I will mention to Jarod to adjust the template width accordingly.

**Comment by yegortimoshenko** [comment]
> If this will automatically redirect to hpstatus then maybe it's not a problem, but I would suggest we just close it and I will mention to Jarod to adjust the template width accordingly.

Aha, I see. I'll tweak the template width then.

**Comment by yegortimoshenko** [comment]
Bumped template width to 640, this is not an issue anymore. Thank you for explaining me the rationale.
