### ISSUE TITLE
Implement status check in Client calls to the Server

### ISSUE THREAD

**Issue by peeech** [Holo-Host/holo-auth#17]
Currently Client [makes a call](https://github.com/Holo-Host/holo-auth/blob/develop/client/src/main.rs#L43) to Holo-Auth Server in a happy mode. Accounting for edge cases will improve reliability of the service.

Possible failures (networking timeout, Postmart failure) could result in a retry.

**Comment by yegortimoshenko** [comment]
Duplicate of #16.
