### ISSUE TITLE
Worker does case-sensitive match of email address against whitelist

### ISSUE THREAD

**Issue by pdaoust** [Holo-Host/holo-auth#23]
A HoloPort owner was having trouble registering his email address because he started it with a capital letter, whereas the whitelist had it in all lower-case. I see that [the worker doesn't do any normalisation for upper/lower case](https://github.com/Holo-Host/holo-auth/blob/develop/server/src/routes/challenge.js#L12), and indeed it can only normalise the email address in the user's registration request, not the whitelisted email address.

Most email servers don't enforce case-sensitive addresses, so `Paul.dAoust@Holo.Host` should be functionally identical to `paul.daoust@holo.host` for 98% of servers on the planet. I feel that we should offer that same consistency.

But I'm not sure what to recommend, because you can't normalise the whitelisted email addresses -- it's a key in the K/V store, after all. We could require C/S staff to always input email addresses in lower-case; that might help, but it's error-prone.

CC @yegortimoshenko @alastairong

**Comment by yegortimoshenko** [comment]
Confirming the issue. Thank you for the report.

**Comment by yegortimoshenko** [comment]
Resolved in af64bcedc5bf9689e840eecfc362aae2cf81fbcd. Will be automatically deployed in the next 10 minutes.

**Comment by yegortimoshenko** [comment]
Deployed.

**Comment by pdaoust** [comment]
Woo, thanks! So this is one half of the fix; I'll tell everyone in support to enter emails lower-case only, and I'll write a script to update all the existing white listed emails in place on Monday. Could this action cause any negative interactions, e.g., with the email addresses listed in the registered ZT devices? Would it be safer to just add new lower-case addresses and keep the upper-case ones in the K/V store as-is?

**Comment by yegortimoshenko** [comment]
> Woo, thanks! So this is one half of the fix; I'll tell everyone in support to enter emails lower-case only, and I'll write a script to update all the existing white listed emails in place on Monday. 

You sure you want/have time to do that? Feel free to delegate to me if you'd rather do something else.

> Could this action cause any negative interactions, e.g., with the email addresses listed in the registered ZT devices?

No, not really; email addresses in ZeroTier are for reference only.

> Would it be safer to just add new lower-case addresses and keep the upper-case ones in the K/V store as-is?

I think we should overwrite non-lowercase emails in the KV store.

**Comment by pdaoust** [comment]
Thanks for the offer -- however i ended up writing the script this morning before I saw your reply. It only took me about five minutes to write the script (I'd already written half of it for something I was working on yesterday). Turns out there were only two whitelisted email addresses with capitals in them.
