### ISSUE TITLE
Implement ZeroTier status check

### ISSUE THREAD

**Issue by alpakido** [Holo-Host/holo-auth#3]
During client Rust rewrite, I forgot to add in ZeroTier status check:

https://github.com/Holo-Host/holo-nixpkgs/blob/b33dc9a4718ed7d1a5859b6b5eb3f7289b6cbb82/overlays/holo-nixpkgs/holo-auth-client/holo-auth-client.py#L54-L57

It should be added back in.

**Comment by yegortimoshenko** [comment]
Subject to implementing transumption/zerotier-rust#1.

**Comment by peeech** [comment]
done
