### ISSUE TITLE
Import emails into Holo Auth whitelist

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-auth#4]
Whitelist KV store is currently empty. It needs to be populated with data from Freshdesk. Write an import tool, run it, and commit it to this repo.

https://github.com/Holo-Host/holo-auth/blob/9fd2c43b04786bd292026775614ed343a10d7f4b/server/wrangler.toml#L12-L14

**Comment by yegortimoshenko** [comment]
cc @alastairong

**Comment by peeech** [comment]
Do you have any plan how to execute it? I know there's some filtering process needed between freshdesk and Whitelist KV store. AFAIK filtering is based on Freshdesk user properties therefore I think it can be automated.

For example this is the place where already registered users can be filtered out.

@yegortimoshenko @marycamacho

**Comment by yegortimoshenko** [comment]
Already registered users don't need to be filtered out. Again, this is not something that would be re-triggered unless user was de-authorized from ZeroTier for whatever reason.

**Comment by yegortimoshenko** [comment]
> Do you have any plan how to execute it?

Sure, read data from one service, write it to another. The shape of data that needs to be important can be looked up in `holoport-authorizer`.

**Comment by yegortimoshenko** [comment]
Resolved by #10.
