### ISSUE TITLE
Decide on interface for whitelist support

### ISSUE THREAD

**Issue by yegortimoshenko** [Holo-Host/holo-auth#5]
We can't read this data from Freshdesk anymore because [their API rate limit](https://developers.freshdesk.com/api/#ratelimit) is extremely low and Paul's `holoport-authorizer` was regularly hitting it, which was one of the things that were causing reliability issues. In addition to that, Freshdesk is a support system, and was not created for the purpose of being a source of truth for any data.

Let's decide on UI to offer support to add/remove whitelist entries. I'd recommend to start with updating whitelist KV store directly. Here's what it would take to add a new whitelist entry:

1. Open [holo-auth-server-whitelist KV store](https://dash.cloudflare.com/18ff2b4e6205b938652998cfca0d8cff/workers/kv/namespaces/3130e2ca2d234214ba9db91622f7f197).
2. Input email into "Key" field.
    ![Screenshot from 2020-01-28 05-19-48.png](https://images.zenhubusercontent.com/5e1d3b96a8ad747eecd00629/ef5c3223-2c7c-44a1-973f-da8f8e92ff9f)
3. Press "Add entry".

To remove a whitelist entry:

1. Choose an entry to remove.
2. Press "..." icon.
3. Click "Delete".
    ![Screenshot from 2020-01-28 05-22-06.png](https://images.zenhubusercontent.com/5e1d3b96a8ad747eecd00629/a5889904-d2e6-4a1f-866e-0ed4cf29b8ab)

cc @alastairong

**Comment by peeech** [comment]
It is possible to get all contacts in one shot from [freshdesk API](https://developers.freshdesk.com/api/#list_all_contacts): /api/v2/contacts?company_id=our_company_id, where our_company_id is a certain int that was assigned to those with access to forum. Are we even still using freshdesk forum??

What needs to be checked is how whitelisting is correlated to signing up to freshdesk and how to keep it permanently synced. @yegortimoshenko @marycamacho

**Comment by alastairong** [comment]
The whitelist is a subset of the Freshdesk sign ups.

**Comment by yegortimoshenko** [comment]
> It is possible to get all contacts in one shot from freshdesk API: /api/v2/contacts?company_id=our_company_id, where our_company_id is a certain int that was assigned to those with access to forum. Are we even still using freshdesk forum??

This probably belongs more to #4.

> What needs to be checked is how whitelisting is correlated to signing up to freshdesk and how to keep it permanently synced.

This is jumping to a specific solution. We might not want to use Freshdesk at all for whitelisting, because syncing data is error-prone, requires polling, and incurs additional ops overhead. We might just import once and edit KV store directly, or offer a UI to edit KV store directly. TBH, I'd prefer if we don't sync up, unless we really want to keep using Freshdesk for this for other reason.

**Comment by yegortimoshenko** [comment]
And, another possible solution is syncing data from Freshdesk over to KV Store. That is hacky IMO because of disadvantages discussed above. We will probably only be able to do it on schedule. If we end up going this route, #4 will serve as foundation for implementing syncing service.

**Comment by alastairong** [comment]
I've sent this link to @marycamacho and invited her to provide her feedback and ask questions directly.

Here's what Mary's more recent message was:
> We are open to the KV option if we get a CS login and we have explicit instructions and we especially need to understand risk.

@marycamacho Can you elaborate on examples of risks you might be concerned about?

**Comment by marycamacho** [comment]
This seems simple enough. I completely get that a single source of truth not in Freshdesk is important if the API is unreliable. And what you show here seems fine. Risk for me was akin to... 'how easy would it be for a user to accidentally deleted multiple records?' or 'can a user inadvertently (or intentionally) edit other data unrelated to the whitelist when logged in?'

**Comment by marycamacho** [comment]
Can I ask a few tangential questions or is later a better time for that? These questions would relate to the need (or lack thereof) for a host whitelist, the ability to change email/pw on host registrations for future testing, and when we might change the validation limiting more than one HP per email. None of this is urgent.

**Comment by yegortimoshenko** [comment]
> Can I ask a few tangential questions or is later a better time for that?

Sure! Now is great time.

**Comment by alastairong** [comment]
> Risk for me was akin to... 'how easy would it be for a user to accidentally deleted multiple records?' or 'can a user inadvertently (or intentionally) edit other data unrelated to the whitelist when logged in?'

Ok based on this @yegortimoshenko I think the following are the key questions on risk:
1. Can we limit the view and edit permissions on a CS account to this KV store only?
2. How easy would it be to reverse changes (whether accidental or malicious)?
3. Can we limit the CS account to only modifying the contents of the KV store? E.g. they can’t delete the store itself, only make it empty.
4. Am I right in thinking that a big mistake such as clearing the entire store would only impact future registrations, not users who are already completed the holo-auth process?

**Comment by yegortimoshenko** [comment]
> Can we limit the view and edit permissions on a CS account to this KV store only?

Yes.

> How easy would it be to reverse changes (whether accidental or malicious)?

We can make daily backups if we go with direct Cloudflare KV UI access, and we can make audit log with ability to see and reverse any specific change and who did it if we go custom dashboard route (we can eventually upgrade to the latter when we have more time).

> Can we limit the CS account to only modifying the contents of the KV store? E.g. they can’t delete the store itself, only make it empty.

Yes.

> Am I right in thinking that a big mistake such as clearing the entire store would only impact future registrations, not users who are already completed the holo-auth process?

Yes.

**Comment by alastairong** [comment]
@marycamacho Hope those responses answers your immediate questions on risk.

**Comment by yegortimoshenko** [comment]
Cloudflare UI doesn't make it easy to delete or add more than one entry at a time, too.

**Comment by yegortimoshenko** [comment]
Closing as resolved based on https://github.com/Holo-Host/holo-auth/pull/10#issuecomment-580070835. @marycamacho I think it still would be great to discuss all of these tangential questions.

**Comment by alastairong** [comment]
@yegortimoshenko Assuming daily backups have been set up, how do we get Mary a Cloudflare account with write access to this KV store and no read/write access to any other KV store?

**Comment by alastairong** [comment]
@yegortimoshenko Bump re: getting Mary a Cloudflare account. Who's the right person to ask?

**Comment by yegortimoshenko** [comment]
That would be @evangineer. I think, access can be limited to that single KV store (ID `5181f479e6d84fc9835c5195b08a7029`).

**Comment by alastairong** [comment]
Thanks

**Comment by alastairong** [comment]
Mary's input on the poor browser-based UX for deleting entries is that deleting emails from the whitelist (even for changing) is rare vs. adding. She would rather deprecate Freshdesk ASAP so is happy to go along with the Cloudflare interface for now.

**Comment by evangineer** [comment]
Cloudflare access to Workers resources including KV stores granted.  

Details can be found here:
https://trello.com/c/nDlGlwl6

**Comment by alastairong** [comment]
Thanks Mamading!
